# Generated by Django 3.2.8 on 2021-11-29 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CacNuocDiQua', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('company', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Công ty làm việc')),
                ('part', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Bộ phận làm việc')),
                ('BHYT', models.BooleanField(default=False, verbose_name='Có thẻ bảo hiểm y tế')),
                ('Sot', models.BooleanField(default=False, verbose_name='Sốt')),
                ('Ho', models.BooleanField(default=False, verbose_name='Ho')),
                ('KhoTho', models.BooleanField(default=False, verbose_name='Khó thở')),
                ('ViemPhoi', models.BooleanField(default=False, verbose_name='Viêm phổi')),
                ('DauHong', models.BooleanField(default=False, verbose_name='Đau họng')),
                ('Metmoi', models.BooleanField(default=False, verbose_name='Mệt mỏi')),
                ('NghiNgo', models.BooleanField(default=False, verbose_name='Người bệnh hoặc nghi ngờ, mắc bệnh COVID-19 (*)')),
                ('CoBenh', models.BooleanField(default=False, verbose_name='Người từ nước có bệnh COVID-19 (*)')),
                ('CoBieuHien', models.BooleanField(default=False, verbose_name='Người có biểu hiện (Sốt, ho, khó thở, Viêm phổi) (*)')),
                ('Gan', models.BooleanField(default=False, verbose_name='Bệnh gan mãn tính (*)')),
                ('Mau', models.BooleanField(default=False, verbose_name='Bệnh máu mãn tính (*)')),
                ('Phoi', models.BooleanField(default=False, verbose_name='Bệnh phổi mãn tính (*)')),
                ('Than', models.BooleanField(default=False, verbose_name='Bệnh thận mãn tính (*)')),
                ('TimMach', models.BooleanField(default=False, verbose_name='Bệnh tim mạch (*)')),
                ('HuyetApCao', models.BooleanField(default=False, verbose_name='Huyết áp cao (*)')),
                ('SuyGiamMienDich', models.BooleanField(default=False, verbose_name='Suy giảm miễn dịch (*)')),
                ('Ghep', models.BooleanField(default=False, verbose_name='Người nhận ghép tạng, Tủy xương (*)')),
                ('TieuDuong', models.BooleanField(default=False, verbose_name='Tiểu đường (*)')),
                ('UngThu', models.BooleanField(default=False, verbose_name='Ung thư (*)')),
                ('ThaiKy', models.BooleanField(default=False, verbose_name='Bạn có đang trong thời gian thai kỳ hay không? (*)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthdeclare', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
