# Generated by Django 3.2.8 on 2021-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdeclaration',
            name='CacNuocDiQua',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
