# Generated by Django 3.2.8 on 2021-11-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acount',
            name='career',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acount',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
