# Generated by Django 3.2.8 on 2021-11-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_tinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_huyen', models.CharField(blank=True, default='Tên huyện', max_length=50, null=True)),
                ('tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tinh')),
            ],
        ),
    ]
