# Generated by Django 3.2.8 on 2021-11-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='career',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nghề nghiệp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tỉnh, thành phố'),
        ),
        migrations.AlterField(
            model_name='account',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Xã, phường'),
        ),
        migrations.AlterField(
            model_name='account',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Quận, huyện'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='', max_length=6, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(default='CCCD', max_length=50)),
                ('bhyt', models.CharField(default='BHYT', max_length=50)),
                ('ques1', models.BooleanField(default=False, verbose_name='Trong vong 14 ngay qua')),
                ('ques2', models.BooleanField(default=False, verbose_name='Trong vong 14 ngay qua')),
                ('ques3', models.BooleanField(default=False, verbose_name='Trong vong 14 ngay qua')),
                ('ques4', models.BooleanField(default=False, verbose_name='Trong vong 14 ngay qua')),
                ('ques5', models.BooleanField(default=False, verbose_name='Trong vong 14 ngay qua')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('disease', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Bệnh')),
                ('treatment', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Điều trị')),
                ('note', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('Đang điều trị', 'Đang điều trị'), ('Đã điều trị', 'Đã điều trị')], default='Đang điều trị', max_length=20)),
                ('doctorUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('medicalRecordUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
