# Generated by Django 3.2.8 on 2021-11-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20211128_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='accounts.account'),
        ),
    ]
