# Generated by Django 3.2.8 on 2021-11-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_doctor_doctoruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='medicalRecordUser',
            new_name='record',
        ),
    ]
