# Generated by Django 3.2.8 on 2021-11-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20211128_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='record',
            new_name='user',
        ),
    ]
