# Generated by Django 3.2.8 on 2021-11-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211110_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tinh',
        ),
    ]
