# Generated by Django 3.2.8 on 2021-11-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211110_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinh',
            options={'ordering': ['ten_tinh']},
        ),
    ]
