# Generated by Django 3.2.8 on 2021-12-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_pic',
        ),
    ]
