# Generated by Django 3.2.8 on 2021-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_khaibaotrieuchung_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC17',
            field=models.BooleanField(verbose_name='Sốt dưới 39 độ C'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC18',
            field=models.BooleanField(verbose_name='Ho khan, đau họng'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC19',
            field=models.BooleanField(verbose_name='Mệt mỏi nhưng vẫn sinh hoạt bình thường'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC20',
            field=models.BooleanField(verbose_name='Đau nhức cơ thể'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC21',
            field=models.BooleanField(verbose_name='Khó thở nhẹ'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC22',
            field=models.BooleanField(verbose_name='Đau đầu'),
        ),
    ]
