# Generated by Django 3.2.8 on 2021-11-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211110_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_huyen', models.CharField(default='Tên huyện', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tinh', models.CharField(default='Tên tỉnh', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_xa', models.CharField(default='Xã, phường, thị trấn', max_length=50, null=True)),
                ('huyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.huyen')),
                ('tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tinh')),
            ],
        ),
        migrations.AddField(
            model_name='huyen',
            name='tinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tinh'),
        ),
    ]
