# Generated by Django 3.2.8 on 2021-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_diachi'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acount',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acount',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acount',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ')], max_length=6),
        ),
    ]
