# Generated by Django 3.2.8 on 2021-11-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211122_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='account',
            name='career',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nghề nghiệp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tỉnh, thành phố'),
        ),
        migrations.AlterField(
            model_name='account',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xã, phường'),
        ),
        migrations.AlterField(
            model_name='account',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quận, huyện'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ')], default='Nữ', max_length=6, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='card.svg', null=True, upload_to='', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistantUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
