# Generated by Django 3.2.8 on 2021-11-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('BS', 'Bác sĩ'), ('BN', 'Bệnh nhân'), ('K', 'Khác')], default='Khác', max_length=10),
        ),
    ]
