# Generated by Django 3.2.8 on 2021-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nữ', max_length=6, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('Bác sĩ', 'Bác sĩ'), ('Bệnh nhân', 'Bệnh nhân'), ('Khác', 'Khác')], default='Khác', max_length=10),
        ),
    ]
