# Generated by Django 3.2.8 on 2021-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211125_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default='256 Thôn An Hoà', max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='career',
            field=models.CharField(blank=True, default='Sinh viên', max_length=50, null=True, verbose_name='Nghề nghiệp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='Hà Nội', max_length=50, null=True, verbose_name='Tỉnh, thành phố'),
        ),
        migrations.AlterField(
            model_name='account',
            name='commune',
            field=models.CharField(blank=True, default='Xã Bình An', max_length=50, null=True, verbose_name='Xã, phường'),
        ),
        migrations.AlterField(
            model_name='account',
            name='district',
            field=models.CharField(blank=True, default='Huyện Bắc Bình', max_length=50, null=True, verbose_name='Quận, huyện'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='0123456789', max_length=50, null=True, verbose_name='Số điện thoại'),
        ),
    ]
