# Generated by Django 3.2.8 on 2021-11-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211125_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistantUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
