# Generated by Django 3.2.8 on 2021-11-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('Bác sĩ', 'Bác sĩ'), ('Bệnh nhân', 'Bệnh nhân'), ('Khác', 'Khác')], default='Khác', max_length=10),
        ),
    ]
