# Generated by Django 3.2.8 on 2021-11-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_alter_account_type_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayPhatBenh', models.DateField(blank=True, null=True, verbose_name='Ngày phát bệnh')),
                ('LyDo', models.CharField(max_length=200, verbose_name='Lý do nhiễm bệnh')),
                ('SDTNguoiThan', models.CharField(max_length=10, verbose_name='Số điện thoại người thân')),
                ('BenhNen', models.CharField(max_length=200, verbose_name='Bệnh nền')),
                ('NoiDiQua', models.CharField(max_length=300, verbose_name='Nơi đã đi qua')),
                ('TinhTrang', models.CharField(choices=[('Đang điều trị tại nhà', 'Đang điều trị tại nhà'), ('Đã nhập viện', 'Đã nhập viện'), ('Đã khỏi bệnh', 'Đã khỏi bệnh'), ('Đã tử vong', 'Đã tử vong')], default='Đang điều trị tại nhà', max_length=23, verbose_name='Tình trạng')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
