# Generated by Django 3.2.8 on 2021-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_healthdeclaration_cacnuocdiqua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdeclaration',
            name='CacNuocDiQua',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
