# Generated by Django 3.2.8 on 2021-10-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination_status', models.CharField(choices=[('1', 'One dose'), ('2', 'Two dose'), ('0', 'Not yet')], default='0', max_length=2)),
                ('specialist', models.CharField(default='specialist', max_length=50)),
                ('hospital', models.CharField(blank=True, default='specialist', max_length=50)),
                ('doctorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fullname'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination_status', models.CharField(choices=[('1', 'One dose'), ('2', 'Two dose'), ('0', 'Not yet')], default='0', max_length=2)),
                ('diagnosisDate', models.DateTimeField(blank=True, null=True)),
                ('relativePhoneNum', models.CharField(blank=True, max_length=10, null=True)),
                ('doctorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.doctor')),
                ('patientUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fullname'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination_status', models.CharField(choices=[('1', 'One dose'), ('2', 'Two dose'), ('0', 'Not yet')], default='0', max_length=2)),
                ('otherUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fullname'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination_status', models.CharField(choices=[('1', 'One dose'), ('2', 'Two dose'), ('0', 'Not yet')], default='0', max_length=2)),
                ('assistantUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.doctor')),
            ],
            options={
                'ordering': ['fullname'],
                'abstract': False,
            },
        ),
    ]
