# Generated by Django 3.2.8 on 2021-10-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordID', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prescriptionDate', models.DateTimeField(auto_now_add=True)),
                ('time', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('doctorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.doctor')),
                ('patientUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('producer', models.CharField(blank=True, max_length=50, null=True)),
                ('distributor', models.CharField(blank=True, max_length=50, null=True)),
                ('nation', models.CharField(blank=True, max_length=50, null=True)),
                ('decription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MRDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalQuantity', models.IntegerField()),
                ('morning', models.IntegerField(null=True)),
                ('evening', models.IntegerField(null=True)),
                ('night', models.IntegerField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('medicineName', models.ManyToManyField(to='CareApp.Medicine')),
                ('recordID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.medicalrecord')),
            ],
        ),
    ]
