# Generated by Django 3.2.8 on 2021-10-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0002_medicalrecord_medicine_mrdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSymptom', models.CharField(blank=True, default='symptom', max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordID', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('timeModified', models.DateTimeField(auto_now_add=True)),
                ('statePredict', models.CharField(choices=[('B', 'Blue'), ('Y', 'Yellow'), ('R', 'Red')], default='B', max_length=1)),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SDDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.BooleanField(default=False)),
                ('nameSymptom', models.ManyToManyField(to='CareApp.Symptom')),
                ('recordID', models.ForeignKey(blank=True, default='symptom', on_delete=django.db.models.deletion.CASCADE, to='CareApp.symptomdeclaration')),
            ],
        ),
    ]
