# Generated by Django 3.2.8 on 2021-12-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0036_auto_20211206_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaiBaoTrieuChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC1', models.BooleanField(verbose_name='Các triệu chứng thường gặp (khởi phát) nặng lên liên tục không đỡ')),
                ('TC2', models.BooleanField(verbose_name='Sốt cao từ 39 độ C không đáp ứng với thuốc hạ sốt (sốt trở lại trong vòng 02h sau dùng thuốc)')),
                ('TC3', models.BooleanField(verbose_name='Khó thở không thể làm việc được phải nghỉ ngơi')),
                ('TC4', models.BooleanField(verbose_name='Mệt mỏi, sinh hoạt khó khăn')),
                ('TC5', models.BooleanField(verbose_name='Huyết áp tăng cao từ 160/100 mmHG không đáp ứng với thuốc thường dùng')),
                ('TC6', models.BooleanField(verbose_name='Đo huyết áp 2 lần có giá trị trung bình dưới 85/5mmHG')),
                ('TC7', models.BooleanField(verbose_name='Nhịp tim tăng cao trên 120 lần/phút hoặc xuống dưới 50 lần/phút, hoặc nhịp thở từ 25 lần/phút')),
                ('TC8', models.BooleanField(verbose_name='Khó thở nhiều không thể nằm để thở')),
                ('TC9', models.BooleanField(verbose_name="Đau tức ngực thành cơn kéo dài từ 5'")),
                ('TC10', models.BooleanField(verbose_name='Mất khả năng nói hoặc cử động')),
                ('TC11', models.BooleanField(verbose_name='Lơ mơ, không tỉnh táo')),
                ('TC12', models.BooleanField(verbose_name='SpO2 < 94% khi nghỉ hoặc tụt ')),
                ('TC13', models.BooleanField(verbose_name='')),
                ('TC14', models.BooleanField(verbose_name='')),
                ('TC15', models.BooleanField(verbose_name='')),
                ('TC16', models.BooleanField(verbose_name='')),
                ('TC17', models.BooleanField(verbose_name='')),
                ('TC18', models.BooleanField(verbose_name='')),
                ('TC19', models.BooleanField(verbose_name='')),
                ('TC20', models.BooleanField(verbose_name='')),
                ('TC21', models.BooleanField(verbose_name='')),
                ('TC22', models.BooleanField(verbose_name='')),
                ('TC23', models.BooleanField(verbose_name='')),
                ('TC24', models.BooleanField(verbose_name='')),
                ('TC25', models.BooleanField(verbose_name='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
