# Generated by Django 3.2.8 on 2021-12-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaibaotrieuchung',
            name='TC24',
        ),
        migrations.RemoveField(
            model_name='khaibaotrieuchung',
            name='TC25',
        ),
        migrations.AddField(
            model_name='khaibaotrieuchung',
            name='DanhGia',
            field=models.CharField(choices=[('Xanh', 'Xanh'), ('Vàng', 'Vàng'), ('Đỏ', 'Đỏ')], default='Xanh', max_length=23, verbose_name='Đánh giá: '),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC12',
            field=models.BooleanField(verbose_name='SpO2 < 94% khi nghỉ hoặc tụt SpO2 xuống < 94% sau gắng sức (nếu có thiết bị đo SpO2 tại nhà'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC13',
            field=models.BooleanField(verbose_name='Tiêu chảy'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC14',
            field=models.BooleanField(verbose_name='Viêm kết mạc'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC15',
            field=models.BooleanField(verbose_name='Mất vị giác hoặc khứu giác'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC16',
            field=models.BooleanField(verbose_name='Da nổi mẩn hay ngón tay hoặc ngón chân bị tất đỏ hoặc tím tái'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC17',
            field=models.BooleanField(verbose_name='Có bệnh nền tim mạch, ho hấp đang điều trị'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC18',
            field=models.BooleanField(verbose_name='Có bệnh lý ung thư mạn tính đang điều trị'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC19',
            field=models.BooleanField(verbose_name='Có bệnh lý suy thận mạn tính đang điều trị'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC20',
            field=models.BooleanField(verbose_name='Viêm gan đang hoạt động, suy giảm chức năng gan'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC21',
            field=models.BooleanField(verbose_name='Người cao tuổi từ 65 tuổi trở lên'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC22',
            field=models.BooleanField(verbose_name='Thừa cân, béo phì với BMI từ 25kg/cm2 trở lên'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC23',
            field=models.BooleanField(verbose_name='Xác nhận không có triệu chứng gì trong các triệu chứng kệ trên'),
        ),
    ]
