# Generated by Django 3.2.8 on 2021-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20211206_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaibaotrieuchung',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Ngày khai báo'),
        ),
    ]
