# Generated by Django 3.2.8 on 2021-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20211206_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaibaotrieuchung',
            name='Note',
            field=models.TextField(max_length=500, null=True, verbose_name='Ghi chú'),
        ),
    ]
