# Generated by Django 3.2.8 on 2021-12-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20211206_1343'),
        ('patient', '0005_khaibaotrieuchung_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaibaotrieuchung',
            name='DanhGia',
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DanhGia', models.CharField(choices=[('Xanh', 'Xanh'), ('Vàng', 'Vàng'), ('Đỏ', 'Đỏ')], default='Xanh', max_length=23, verbose_name='Đánh giá: ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
