# Generated by Django 3.2.8 on 2021-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20211207_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='DanhGia',
            field=models.CharField(blank=True, choices=[('Xanh', 'Xanh'), ('Vàng', 'Vàng'), ('Đỏ', 'Đỏ')], default='Xanh', max_length=23, null=True, verbose_name='Đánh giá: '),
        ),
    ]
