# Generated by Django 3.2.8 on 2021-12-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20211207_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC7',
            field=models.BooleanField(default=False, verbose_name='Nhịp tim tăng cao trên 120 lần/phút hoặc xuống dưới 50 lần/phút, hoặc nhịp thở từ 25 lần/phút'),
        ),
    ]
