# Generated by Django 3.2.8 on 2021-11-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211110_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaChi',
        ),
    ]
