# Generated by Django 3.2.8 on 2021-11-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctorUser',
            new_name='patientUser',
        ),
    ]
