# Generated by Django 3.2.8 on 2021-12-05 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
