# Generated by Django 3.2.8 on 2021-12-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_danhgia_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='date',
        ),
        migrations.RemoveField(
            model_name='khaibaotrieuchung',
            name='date',
        ),
    ]
