# Generated by Django 3.2.8 on 2021-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20211207_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='DanhGia',
            field=models.CharField(choices=[('Xanh', 'Xanh'), ('Vàng', 'Vàng'), ('Đỏ', 'Đỏ')], default='Xanh', max_length=23, verbose_name='Đánh giá: '),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC1',
            field=models.BooleanField(default=False, verbose_name='Các triệu chứng thường gặp (khởi phát) nặng lên liên tục không đỡ'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC10',
            field=models.BooleanField(default=False, verbose_name='Mất khả năng nói hoặc cử động'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC11',
            field=models.BooleanField(default=False, verbose_name='Lơ mơ, không tỉnh táo'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC12',
            field=models.BooleanField(default=False, verbose_name='SpO2 < 94% khi nghỉ hoặc tụt SpO2 xuống < 94% sau gắng sức (nếu có thiết bị đo SpO2 tại nhà'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC13',
            field=models.BooleanField(default=False, verbose_name='Tiêu chảy'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC14',
            field=models.BooleanField(default=False, verbose_name='Viêm kết mạc'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC15',
            field=models.BooleanField(default=False, verbose_name='Mất vị giác hoặc khứu giác'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC16',
            field=models.BooleanField(default=False, verbose_name='Da nổi mẩn hay ngón tay hoặc ngón chân bị tất đỏ hoặc tím tái'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC17',
            field=models.BooleanField(default=False, verbose_name='Sốt dưới 39 độ C'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC18',
            field=models.BooleanField(default=False, verbose_name='Ho khan, đau họng'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC19',
            field=models.BooleanField(default=False, verbose_name='Mệt mỏi nhưng vẫn sinh hoạt bình thường'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC2',
            field=models.BooleanField(default=False, verbose_name='Sốt cao từ 39 độ C không đáp ứng với thuốc hạ sốt (sốt trở lại trong vòng 02h sau dùng thuốc)'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC20',
            field=models.BooleanField(default=False, verbose_name='Đau nhức cơ thể'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC21',
            field=models.BooleanField(default=False, verbose_name='Khó thở nhẹ'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC22',
            field=models.BooleanField(default=False, verbose_name='Đau đầu'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC23',
            field=models.BooleanField(default=False, verbose_name='Xác nhận không có triệu chứng gì trong các triệu chứng kệ trên'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC3',
            field=models.BooleanField(default=False, verbose_name='Khó thở không thể làm việc được phải nghỉ ngơi'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC4',
            field=models.BooleanField(default=False, verbose_name='Mệt mỏi, sinh hoạt khó khăn'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC5',
            field=models.BooleanField(default=False, verbose_name='Huyết áp tăng cao từ 160/100 mmHG không đáp ứng với thuốc thường dùng'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC6',
            field=models.BooleanField(default=False, verbose_name='Đo huyết áp 2 lần có giá trị trung bình dưới 85/5mmHG'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC8',
            field=models.BooleanField(default=False, verbose_name='Khó thở nhiều không thể nằm để thở'),
        ),
        migrations.AlterField(
            model_name='khaibaotrieuchung',
            name='TC9',
            field=models.BooleanField(default=False, verbose_name="Đau tức ngực thành cơn kéo dài từ 5'"),
        ),
    ]
