# Generated by Django 3.2.8 on 2021-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_home', models.IntegerField()),
                ('count_hospital', models.IntegerField()),
                ('count_ok', models.IntegerField()),
                ('count_dead', models.IntegerField()),
            ],
        ),
    ]
