# Generated by Django 3.2.8 on 2021-11-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
