# Generated by Django 3.2.8 on 2021-12-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20211206_1343'),
        ('doctor', '0003_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medical', verbose_name='Tên thuốc')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
