# Generated by Django 3.2.8 on 2021-12-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_medicalrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
