# Generated by Django 3.2.8 on 2021-12-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20211206_1343'),
        ('doctor', '0005_delete_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.IntegerField(verbose_name='Liều')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày')),
                ('note', models.CharField(max_length=500, verbose_name='Ghi chú')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medical', verbose_name='Tên thuốc')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
