# Generated by Django 3.2.8 on 2021-12-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='medical',
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
    ]
