# Generated by Django 3.2.8 on 2021-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_medicalrecord_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ghi chú'),
        ),
    ]
