# Generated by Django 3.2.8 on 2021-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_medicalrecord_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='d1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 1'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 10'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 2'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 3'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 4'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 5'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 6'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 7'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 8'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='d9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liều 9'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 1'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 10'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 2'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 3'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 4'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 5'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 6'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 7'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 8'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='m9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc 9'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú'),
        ),
    ]
