# Generated by Django 3.2.8 on 2021-11-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tinh_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xa',
            name='huyen',
        ),
        migrations.RemoveField(
            model_name='xa',
            name='tinh',
        ),
        migrations.DeleteModel(
            name='Huyen',
        ),
        migrations.DeleteModel(
            name='Tinh',
        ),
        migrations.DeleteModel(
            name='Xa',
        ),
    ]
