# Generated by Django 3.2.8 on 2021-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_account_type_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='CMND',
            field=models.CharField(blank=True, default='Chưa có', max_length=50, null=True, verbose_name='CMND/CCCD'),
        ),
    ]
