# Generated by Django 3.2.8 on 2021-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='card.svg', upload_to=''),
        ),
    ]
